# Cette fonction recrée un arbre de Huffman à partir des codes binaires de chaque caractère
def reconstruire_arbre_depuis_codes(codes):
    racine = {}

        # On parcourt tous les caractères et leurs codes (ex: 'a': '10')
            for char, code in codes.items():
                    noeud = racine  # On part de la racine à chaque caractère

                            # Pour chaque bit du code ('0' ou '1'), on construit des branches dans un dictionnaire
                                    for bit in code:
                                                if bit not in noeud:
                                                                noeud[bit] = {}
                                                                            noeud = noeud[bit]  # On avance dans l’arbre

                                                                                    # Quand on arrive au bout du code, on place le caractère
                                                                                            noeud['char'] = char

                                                                                                return racine

                                                                                                # Cette fonction utilise l’arbre pour convertir une chaîne binaire compressée en texte normal
                                                                                                def decoder_texte(binaire, arbre):
                                                                                                    texte = ''
                                                                                                        noeud = arbre  # On commence à la racine

                                                                                                            # On lit chaque bit de la chaîne compressée
                                                                                                                for bit in binaire:
                                                                                                                        noeud = noeud[bit]  # On descend dans l’arbre selon le bit

                                                                                                                                # Si on trouve une feuille (le caractère), on l’ajoute au texte
                                                                                                                                        if 'char' in noeud:
                                                                                                                                                    texte += noeud['char']
                                                                                                                                                                noeud = arbre  # On revient à la racine pour recommencer

                                                                                                                                                                    return texte# Cette fonction recrée un arbre de Huffman à partir des codes binaires de chaque caractère
                                                                                                                                                                    def reconstruire_arbre_depuis_codes(codes):
                                                                                                                                                                        racine = {}

                                                                                                                                                                            # On parcourt tous les caractères et leurs codes (ex: 'a': '10')
                                                                                                                                                                                for char, code in codes.items():
                                                                                                                                                                                        noeud = racine  # On part de la racine à chaque caractère

                                                                                                                                                                                                # Pour chaque bit du code ('0' ou '1'), on construit des branches dans un dictionnaire
                                                                                                                                                                                                        for bit in code:
                                                                                                                                                                                                                    if bit not in noeud:
                                                                                                                                                                                                                                    noeud[bit] = {}
                                                                                                                                                                                                                                                noeud = noeud[bit]  # On avance dans l’arbre

                                                                                                                                                                                                                                                        # Quand on arrive au bout du code, on place le caractère
                                                                                                                                                                                                                                                                noeud['char'] = char

                                                                                                                                                                                                                                                                    return racine

                                                                                                                                                                                                                                                                    # Cette fonction utilise l’arbre pour convertir une chaîne binaire compressée en texte normal
                                                                                                                                                                                                                                                                    def decoder_texte(binaire, arbre):
                                                                                                                                                                                                                                                                        texte = ''
                                                                                                                                                                                                                                                                            noeud = arbre  # On commence à la racine

                                                                                                                                                                                                                                                                                # On lit chaque bit de la chaîne compressée
                                                                                                                                                                                                                                                                                    for bit in binaire:
                                                                                                                                                                                                                                                                                            noeud = noeud[bit]  # On descend dans l’arbre selon le bit

                                                                                                                                                                                                                                                                                                    # Si on trouve une feuille (le caractère), on l’ajoute au texte
                                                                                                                                                                                                                                                                                                            if 'char' in noeud:
                                                                                                                                                                                                                                                                                                                        texte += noeud['char']
                                                                                                                                                                                                                                                                                                                                    noeud = arbre  # On revient à la racine pour recommencer

                                                                                                                                                                                                                                                                                                                                        return texte# Cette fonction recrée un arbre de Huffman à partir des codes binaires de chaque caractère
                                                                                                                                                                                                                                                                                                                                        def reconstruire_arbre_depuis_codes(codes):
                                                                                                                                                                                                                                                                                                                                            racine = {}

                                                                                                                                                                                                                                                                                                                                                # On parcourt tous les caractères et leurs codes (ex: 'a': '10')
                                                                                                                                                                                                                                                                                                                                                    for char, code in codes.items():
                                                                                                                                                                                                                                                                                                                                                            noeud = racine  # On part de la racine à chaque caractère

                                                                                                                                                                                                                                                                                                                                                                    # Pour chaque bit du code ('0' ou '1'), on construit des branches dans un dictionnaire
                                                                                                                                                                                                                                                                                                                                                                            for bit in code:
                                                                                                                                                                                                                                                                                                                                                                                        if bit not in noeud:
                                                                                                                                                                                                                                                                                                                                                                                                        noeud[bit] = {}
                                                                                                                                                                                                                                                                                                                                                                                                                    noeud = noeud[bit]  # On avance dans l’arbre

                                                                                                                                                                                                                                                                                                                                                                                                                            # Quand on arrive au bout du code, on place le caractère
                                                                                                                                                                                                                                                                                                                                                                                                                                    noeud['char'] = char

                                                                                                                                                                                                                                                                                                                                                                                                                                        return racine

                                                                                                                                                                                                                                                                                                                                                                                                                                        # Cette fonction utilise l’arbre pour convertir une chaîne binaire compressée en texte normal
                                                                                                                                                                                                                                                                                                                                                                                                                                        def decoder_texte(binaire, arbre):
                                                                                                                                                                                                                                                                                                                                                                                                                                            texte = ''
                                                                                                                                                                                                                                                                                                                                                                                                                                                noeud = arbre  # On commence à la racine

                                                                                                                                                                                                                                                                                                                                                                                                                                                    # On lit chaque bit de la chaîne compressée
                                                                                                                                                                                                                                                                                                                                                                                                                                                        for bit in binaire:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                noeud = noeud[bit]  # On descend dans l’arbre selon le bit

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Si on trouve une feuille (le caractère), on l’ajoute au texte
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if 'char' in noeud:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            texte += noeud['char']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        noeud = arbre  # On revient à la racine pour recommencer

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return texte